# Generated by Django 5.2.4 on 2025-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awzm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foo",
            name="number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
