# Generated by Django 5.2.4 on 2025-07-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awzm", "0002_bar_number_foo_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="foo",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="awzm.foo"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bar",
            name="number",
            field=models.IntegerField(choices=[(1, "One"), (2, "Two")]),
        ),
    ]
