# Generated by Django 5.2.4 on 2025-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awzm", "0003_bar_foo_alter_bar_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="name",
            field=models.CharField(default="", max_length=12),
            preserve_default=False,
        ),
    ]
